version: '3.2'
services:
  mlflow:
    image:  docker.pkg.github.com/andrashee/mlflow-docker/mlflow:development
    build:
      context: .
    depends_on:
      - postgres
      - minio
    ports:
      - 5222:5222
    environment:
      PORT: 5222
      BACKEND_STORE_URI: postgresql://postgres:mlflow@postgres/mlflow
      DEFAULT_ARTIFACT_ROOT: s3://mlflow/mlflow/
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: mlflow
      AWS_SECRET_ACCESS_KEY: mlflow

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mlflow
      - POSTGRES_DB=mlflow
    ports:
      - 5432:5432

  minio:
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z
    environment:
      MINIO_ACCESS_KEY: mlflow_accesskey
      MINIO_SECRET_KEY: mlflow_secretkey
    ports:
      - 9000:9000
    volumes:
      - ./.data/minio:/data
    entrypoint: sh
    command: -c '/usr/bin/minio server /data'
